{% set name = "halo" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8aeb0164e269d7c96fb7444b2a4caaa09b8989fa0c85e6a26e8b2c6d1af3b9d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - colorama >=0.3.9
    - cursor >=1.2.0
    - log_symbols >=0.0.14
    - python >=3.5
    - six >=1.12.0
    - spinners >=0.0.24
    - termcolor >=1.1.0

test:
  imports:
    - halo

about:
  home: https://github.com/manrajgrover/halo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Beautiful terminal spinners in Python

extra:
  recipe-maintainers:
    - duncanmmacleod
